server:
  port: 8090
spring:
  data:
    mongodb:
      username: spring_ecommerce
      password: pass123
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
